In [66]:
"""
pytorch基础入门教程/一小时学会pytorch
https://blog.csdn.net/weixin_41070748/article/details/89890330
"""
import torch

In [67]:
torch.empty(3, 2)  # 约 0 张量
torch.rand(2, 4)  # 0 ~ 1 张量
torch.rand(2, 4)  # all 1 张量
torch.zeros(4, 2, dtype=torch.long)  # 0 张量
x = torch.tensor([5.5, 3])  # 张量

In [68]:
x.new_ones(2, 3, dtype=torch.double)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [109]:
torch.randn_like(x, dtype=torch.float)  # 不变IJ 随机 override

tensor([0.0506, 0.0285])

In [110]:
x.size()

torch.Size([2])

In [147]:
# 运算
x = torch.zeros(2, 3)
y = torch.tensor(2)

x + y, x.add_(y), torch.add(x, y)

(tensor([[2., 2., 2.],
         [2., 2., 2.]]),
 tensor([[2., 2., 2.],
         [2., 2., 2.]]),
 tensor([[4., 4., 4.],
         [4., 4., 4.]]))

In [153]:
x[:, 1], x.numpy()

(tensor([2., 2.]),
 array([[2., 2., 2.],
        [2., 2., 2.]], dtype=float32))

In [212]:
a = torch.randn(2, 2, requires_grad=True)
# a.requires_grad_(True)
b = (a * a).sum()  # b依赖a，a要先grad
a, a * a, b, b.grad_fn, b.grad

(tensor([[-0.0852,  1.5737],
         [ 0.2983,  0.6377]], requires_grad=True),
 tensor([[0.0073, 2.4766],
         [0.0890, 0.4067]], grad_fn=<MulBackward0>),
 tensor(2.9794, grad_fn=<SumBackward0>),
 None)

In [217]:
a = torch.matmul(torch.rand(4, 2), torch.rand(2, 3))  # 矩阵 乘法，mul => matmul

a, a.view(-1)  # 拍成 一维

(tensor([[1.1386, 1.0869, 0.9224],
         [0.6802, 0.6149, 0.4841],
         [1.1407, 1.0530, 0.8544],
         [1.0089, 0.8756, 0.6474]]),
 tensor([1.1386, 1.0869, 0.9224, 0.6802, 0.6149, 0.4841, 1.1407, 1.0530, 0.8544,
         1.0089, 0.8756, 0.6474]))

In [221]:
torch.randn(2, 1, 5, 5)

tensor([[[[ 0.4614, -0.8068, -0.2438, -0.5513, -0.0028],
          [ 0.0667, -0.6298,  0.4750,  0.5933, -2.3629],
          [-0.9809, -0.0284, -0.4637,  0.6255, -0.7987],
          [-0.6900, -0.7163, -0.6089, -0.6710, -0.1413],
          [ 0.3417, -0.6814,  2.2008, -0.3490, -0.6435]]],


        [[[-0.5305, -0.5723, -0.4177,  1.3227,  0.1000],
          [ 0.4086,  0.5589, -0.0355,  0.0661,  0.3269],
          [-0.8407,  0.5186,  0.5709,  1.4014, -1.7009],
          [ 0.8866, -0.4041, -0.8929,  0.7714,  0.8958],
          [ 1.4706,  0.3797,  1.3271,  0.4659,  0.6642]]]])

In [248]:
x = torch.randn(2, 3, 4)
x, x.view(1, 1, -1)

(tensor([[[ 0.5566, -0.8171, -0.6785, -0.3972],
          [ 0.4530,  1.7278, -2.0461, -1.8756],
          [-1.0620,  0.0249,  0.5052,  0.6822]],
 
         [[-0.4782, -0.6567,  0.4541, -1.6549],
          [ 0.5557,  1.3050, -0.5859, -0.9273],
          [ 1.4149,  0.1985, -0.7836, -0.2760]]]),
 tensor([[[ 0.5566, -0.8171, -0.6785, -0.3972,  0.4530,  1.7278, -2.0461,
           -1.8756, -1.0620,  0.0249,  0.5052,  0.6822, -0.4782, -0.6567,
            0.4541, -1.6549,  0.5557,  1.3050, -0.5859, -0.9273,  1.4149,
            0.1985, -0.7836, -0.2760]]]))